local utils = require("...utils").set_transparent
local c = require("...colors")
local cfg = require("...config")

local base = {
    Normal = {fg = c.fg, bg = set_transparent(c.bg)},
    SignColumn = {fg = c.blue, bg = c.none},
    EndOfBuffer = {fg = c.iu_grey},
    NormalFloat = {fg = c.fg, bg = c.grey},
    FloatBorder = {fg = c.blue, bg = c.grey},
    ColorColumn = {fg = c.none, bg = c.grey},
    Conceal = {fg = c.blue},
    Cursor = {fg = c.blue, bg = c.none, style = "reverse"},
    CursorIM = {fg = c.blue, bg = c.none, style = "reverse"},
    Directory = {fg = c.yellow, bg = c.none, style = cfg.bold},
    DiffAdd = {fg = c.blue, bg = c.none, style = "reverse"},
    DiffChange = {fg = c.green, bg = c.none, style = "reverse"},
    DiffDelete = {fg = c.red, bg = c.none, style = "reverse"},
    DiffText = {fg = c.red, bg = c.none, style = "reverse"},
    ErrorMsg = {fg = c.red},
    Folded = {fg = c.fg, bg = c.bg},
    FoldColumn = {fg = c.fg, bg = c.none},
    IncSearch = {fg = c.fg},
    LineNr = {fg = c.grey},
    CursorLineNr = {fg = c.light_grey},
    MatchParen = {fg = c.red, style = "underline, bold"},
    ModeMsg = {fg = c.blue, style = cfg.bold},
    MoreMsg = {fg = c.blue, style = cfg.bold},
    NonText = {fg = c.green},
    Pmenu = {fg = c.fg, bg = c.bg},
    PmenuSel = {fg = c.orange, style = "bold"},
    PmenuSbar = {fg = c.orange},
    PmenuThumb = {fg = c.orange},
    Question = {fg = c.red, style = cfg.bold},
    QuickFixLine = {fg = c.blue, bg = c.ui_grey, style = "bold, italic"},
    Search = {bg = c.grey},
    SpecialKey = {fg = c.blue},
    SpellBad = {fg = c.red, bg = c.none, style = "italic, undercurl"},
    SpellCap = {fg = c.blue, bg = c.none, style = "italic, undercurl"},
    SpellLocal = {fg = c.blue, bg = c.none, style = "italic, undercurl"},
    SpellRare = {fg = c.blue, bg = c.none, style = "italic, undercurl"},
    StatusLine = {style = "reverse"},
    StatusLineNC = {style = "reverse"},
    StatusLineTerm = {style = "reverse"},
    StatusLineTermNC = {style = "reverse"},
    TabLineFill = {},
    TablineSel = {fg = c.fg, bg = c.bg},
    Tabline = {fg = c.fg},
    Title = {fg = c.green, bg = c.none, style = cfg.bold},
    Visual = {fg = c.none, bg = c.grey},
    VisualNOS = {fg = c.none, bg = c.grey},
    WarningMsg = {fg = c.red, style = cfg.bold},
    WildMenu = {fg = c.bg, bg = c.blue, style = "bold"},
    CursorLine = {bg = c.grey},
    ToolbarLine = {fg = c.fg, bg = c.bg},
    ToolbarButton = {fg = c.fg, bg = c.none, style = "bold"},
    NormalMode = {fg = c.blue, bg = c.none, style = "reverse"},
    InsertMode = {fg = c.green, bg = c.none, style = "reverse"},
    ReplaceMode = {fg = c.red, bg = c.none, style = "reverse"},
    VisualMode = {fg = c.blue, bg = c.none, style = "reverse"},
    VertSplit = {fg = c.bg, bg = c.grey},
    CommandMode = {fg = c.grey, bg = c.none, style = "reverse"},
    Warnings = {fg = c.orange},
    healthError = {fg = c.red},
    healthSuccess = {fg = c.green},
    healthWarning = {fg = c.orange}
}

return base
